### ISSUE TITLE
建议：修改插件生成的文件名

### ISSUE THREAD

**Issue by qyh214** [Kloping/Mirai_Plugins_Auto_Reply#4]
目前插件使用的名字似乎是默认名字
建议改为插件名加版本号的形式

**Comment by Kloping** [comment]
请使用英文的符号&nbsp;尝试&nbsp;目前没有对中文的符号做兼容




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kloping/Mirai_Plugins_Auto_Reply"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月23日(星期二) 晚上11:40
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Kloping/Mirai_Plugins_Auto_Reply] 模糊词是如何使用的 (Issue #4)





 
你好，不太理解模糊词的使用方法。例如我添加词语你好 回复我很好
 
发送你好，可以得到我很好的答复。但是模糊词应该如何添加，我尝试了添加你好%? 却无法得到回复
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by qyh214** [comment]
好的，原问题已被解决。问题已在原问题上修改啦，希望改下生成的插件名字

哦哦，看到新的推送啦……
